[env:esp32dev]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/53.03.11/platform-espressif32.zip
board = esp32dev
framework = arduino

monitor_speed = 115200
upload_speed = 921600

board_build.partitions = partitions.csv

build_flags =
    -Os
    -ffunction-sections
    -fdata-sections
    -Wl,--gc-sections
